### ISSUE TITLE
GH sponsor?

### ISSUE THREAD

**Issue by atweiden** [technomancy/fennel-lang.org#24]
Have you thought about doing the GitHub sponsorship program? Would like to sponsor your work on Fennel.

**Comment by technomancy** [comment]
Hey, thanks for saying this! It's super rewarding to hear that people are using Fennel and benefiting from it.

At this time it's difficult to see how introducing funding to the project would help its development, because it's not yet to the point where anyone could quit their job to work on it, and it would be complicated and potentially contentious to determine how to distribute funds among part-time volunteers. Maybe at some point in the future we could revisit that though!

Right now the best thing you can do to help Fennel is to build cool stuff using it and show it off to people. Thanks!
